[General]
codecs-profiles-selected=Video - H.264 + MP3 (MP4)
filedialog-path=@Variant(\0\0\0\x11\0\0\0Rfile:///home/c0mplex/Downloads/Do.You.Believe.2015.1080p.BluRay.H264.AAC-RARBG.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xff\0\0\0\x15\0\0\x4\x17\0\0\x4\x36\0\0\0\0\0\0\0\x16\0\0\x4\x16\0\0\x4\x35\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\x16\0\0\x4\x16\0\0\x4\x35)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1047 982)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=
size=@Size(526 423)

[RecentsMRL]
list=file:///home/c0mplex/Downloads/VID-20200818-WA0009.mp4, file:///home/c0mplex/Downloads/SANTA%20MARTA-FOT-2004-01.mpg, file:///home/c0mplex/Downloads/VIDEO%20FLIAR-LAURA-JUL04-2001.mpg, file:///home/c0mplex/Downloads/LAURA-MIS%20PRIMEROS%20ANOS-01.mpg, file:///home/c0mplex/Downloads/VALERIA-O3.mpg, file:///home/c0mplex/Downloads/VALERIA-O2.mpg, file:///home/c0mplex/Downloads/VALERIA-O1.mpg, file:///home/c0mplex/Downloads/VALERIA-O, file:///home/c0mplex/.config/nchat/profiles/WhatsAppMd_%2B573243628290/tmp/ACB66E1B02FA2E90FEB560A5A3C7296B.f4v, file:///home/c0mplex/video_Sun__Feb01__09_01_18.mkv, file:///home/c0mplex/Downloads/Do.You.Believe.2015.1080p.BluRay.H264.AAC-RARBG.mp4, http://localhost:2020/, file:///home/c0mplex/Videos/c5d86e5e3b4e27058cc03d7e749c9dc8(1).mp4, file:///home/c0mplex/Videos/El%20poder%20de%20la%20cruz%20-%20Pel%C3%ADcula%20completa%20en%20espa%C3%B1ol%20latino%20-%20Pel%C3%ADcula%20de%20Drama%20%EF%BD%9C%20Adrenalina%20Freezone%20%5BAkOl0Yvk73E%5D.webm, file:///home/c0mplex/Videos/autumn-river-pixel-moewalls-com.mp4, file:///home/c0mplex/Downloads/beep.wav, file:///home/c0mplex/.config/nchat/profiles/WhatsAppMd_%2B573243628290/tmp/AC5A555D10C189A34FC9F6D6567A98AA.f4v, file:///home/c0mplex/.config/nchat/profiles/WhatsAppMd_%2B573243628290/tmp/AC7FF99F737A6520F385E666C129FB29.f4v, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineLissajous/20251119_191859/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineInterference/20251119_191356/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineColorMorph/20251119_190902/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineAmplitudePulse/20251119_190702/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/sinedemo2v2/20251119_190544/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineSimple/20251119_190339/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineWave/20251119_185415/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/SineWave/20251119_184946/Video.mp4, file:///home/c0mplex/Documents/PROGRAMMING/cpp/libraries/swaptube/out/CUDAFreePendulumDemo/20251119_181110/Video.mp4
times=18150, 0, 0, 0, 59930, 0, 0, 0, 56401, 0, 583901, 0, 0, 6411858, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
