;;; gdshader-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gdshader-mode.el

(autoload 'gdshader-mode "gdshader-mode" "\
Major mode for Godot Shaders.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.gdshader\\'" . gdshader-mode))
(register-definition-prefixes "gdshader-mode" '("gdshader-"))

;;; End of scraped data

(provide 'gdshader-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gdshader-mode-autoloads.el ends here
